name: Publish with tag
on:
  push:
    branch: dev
jobs:
  build-test-pack:
    name: Build and test linux code, build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Set up nuget
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Darp-IT/index.json"
      - name: Test
        run: |
          dotnet test test/Darp.Utils.Test.Unit
      - name: Pack
        run: |
          dotnet pack src/Darp.ByteExtensions --configuration Release
          dotnet pack src/Darp.Utils --configuration Release
          dotnet pack src/Darp.Utils.Assets --configuration Release
          dotnet pack src/Darp.Utils.UI --configuration Release
          dotnet pack src/Darp.Utils.Avalonia --configuration Release
          dotnet pack src/Darp.Utils.Logging --configuration Release
          dotnet pack src/Darp.Utils.Serial --configuration Release
          dotnet pack src/Darp.Utils.Reasons --configuration Release
          dotnet pack src/Darp.Utils.Reasons.Generator --configuration Release
      - name: Push
        run: |
          dotnet nuget push "src/Darp.ByteExtensions/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.Assets/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.UI/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.Avalonia/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.Logging/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.Serial/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.Reasons/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
          dotnet nuget push "src/Darp.Utils.Reasons.Generator/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
        