name: Publish with tag
on:
  push:
    branches:
      - dev
jobs:
  build-test-pack:
    name: Build and test linux code, build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Set up nuget
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Darp-IT/index.json"
      - name: Test
        run: |
          dotnet test test/Serilog.Sinks.Seq.Tests
      - name: Pack
        run: |
          dotnet pack src/Darp.Serilog.Sinks.Seq --configuration Release
      - name: Push
        run: |
          dotnet nuget push "src/Darp.Serilog.Sinks.Seq/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
        